services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/var/lib/redis

volumes:
  redis_data: {}
